### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by shipstar** [catalyzeio/training#7]
Unlike the policies repo, there doesn't seem to be a license in here anywhere.

It seems like there's a bit more Catalyze-specific language around being a PaaS vendor and your responsibilities under BAAs in this one, so it's possible this wasn't meant to have the same reach at the policies repo.

Is this meant to be forked / remixed / shared like the policies? Or should I keep my grubby paws off of your sweet, sweet training honey?

**Comment by molsches** [comment]
Nope. We definitely need a license in here too. Let me drop one in. It'll probably be later tonight.

Also, thanks for repping us on Reddit on /r/healthit! Much appreciated.

**Comment by shipstar** [comment]
No rush on my end! Just wanted to make sure it was intended to be forkable before I forked and started updating. Thanks!

**Comment by adamleko** [comment]
The repo now has an explicit `LICENSE.md` file that indicates the content is covered under a Creative Commons license (check the file for details). Thanks for pointing out this oversight.
