### ISSUE TITLE
Dead link to HHA Omnibus commentary

### ISSUE THREAD

**Issue by Pro777** [catalyzeio/training#8]
The href from the word "rules" on https://github.com/catalyzeio/training/blob/3c7bd159cc5a7fb263da084ea0bde65a294b994f/old/hipaa.intro/hipaa_sections/hitech.md results in a 404 on the HHS page.

**Comment by adamleko** [comment]
Fixed in 3daa4ce25b4206cfdcf8d9567a2fbe840e791d5b. Thanks for reporting this.

**Comment by adamleko** [comment]
Rather, I'm not sure that specific commit fixed it, but the link is now to http://www.hhs.gov/news/press/2013pres/01/20130117b.html and that works again.
