### ISSUE TITLE
Dead link to Justice Department Legal versus Civil

### ISSUE THREAD

**Issue by Pro777** [catalyzeio/training#9]
404 on the Justice Department page.

"You can read a very detailed, legal opinion on what [constitutes](http://www.justice.gov/olc/hipaa_final.htm) legal vs civil in the case of HIPAA."

Found in:

https://github.com/catalyzeio/training/blob/3c7bd159cc5a7fb263da084ea0bde65a294b994f/source/sections/HIPAA-breaches/penalties.md

https://github.com/catalyzeio/training/blob/3c7bd159cc5a7fb263da084ea0bde65a294b994f/source/sections/HIPAA-basics/why-all-the-fuss-about-hipaa.md

https://github.com/catalyzeio/training/blob/3c7bd159cc5a7fb263da084ea0bde65a294b994f/source/sections/sections-of-HIPAA/enforcement.md

**Comment by adamleko** [comment]
This was fixed in ec722263eeb28b54dd89b532d26ba998683f1d5c - the new link points to http://www.justice.gov/opcl/privacy-act-1974. Thanks again for the reports!
